version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy
  udagram-api-user:
    build:
      context: ./udagram-api-user
    image: shegsteham/udagram-api-user:v1
  udagram-api-feed:
    build:
      context: ./udagram-api-feed
    image: shegsteham/udagram-api-feed:v1
  frontend:
    build:
      context: ./udagram-frontend
    image: shegsteham/udagram-frontend:v2
