apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-frontend
  name: udagram-frontend
spec:
  replicas: 2
  selector:
      matchLabels:
        app.kubernetes.io/name: udagram-api-frontend
  template:
    metadata:
      labels:
        service: udagram-frontend
        api: external
        app.kubernetes.io/name: udagram-api-frontend
    spec:
      containers:
      - image: shegsteham/udagram-frontend:v2
        name: udagram-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
      restartPolicy: Always
